# Generated by Django 2.2.7 on 2019-11-12 20:38

from django.db import migrations, models
import entries.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=10000)),
                ('price', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=entries.models.get_image_path)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
