# Generated by Django 2.2.7 on 2019-11-13 15:24

from django.db import migrations
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=django.utils.timezone.now, force_format=None, keep_meta=True, quality=0, size=[640, 480], upload_to=''),
            preserve_default=False,
        ),
    ]
