# Generated by Django 2.2.7 on 2019-11-13 15:25

from django.db import migrations, models
import entries.models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20191113_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=entries.models.get_image_path),
        ),
    ]
