# Generated by Django 2.2.7 on 2019-11-14 16:10

from django.db import migrations, models
import entries.models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20191113_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(default='/media/photos/None/noimage.PNG', upload_to=entries.models.get_image_path),
        ),
    ]
